# Generated by Django 5.1.7 on 2025-03-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_student_email_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
