# Generated by Django 5.1.7 on 2025-03-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_student_courses"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
    ]
