# Generated by Django 5.1.7 on 2025-03-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_student_courses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("phone", models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
