# Generated by Django 5.1.7 on 2025-03-14 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_teacher_courses_alter_student_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="courses",
        ),
    ]
